import os
import sys
import tempfile
import uuid
import glob
import shutil
from typing import List
from fastapi import APIRouter, UploadFile, File, Form, HTTPException

from app.core.storage import upload_file_to_bucket

# Add the inner directory to sys.path so core.py can import insat and goes
CROP_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../../cropping_mechanism/cropping_mechanism"))
if CROP_DIR not in sys.path:
    sys.path.append(CROP_DIR)

from core import crop_folder

router = APIRouter(prefix="/universal", tags=["universal"])

@router.post("/crop")
async def crop_satellite_file(
    file: UploadFile = File(...),
    lat: float = Form(...),
    lon: float = Form(...),
    patch_size: int = Form(...)
):
    try:
        # Save the uploaded file to a temporary location
        _, ext = os.path.splitext(file.filename)
        if not ext:
            ext = ".nc"
            
        with tempfile.NamedTemporaryFile(delete=False, suffix=ext) as tmp_file:
            shutil.copyfileobj(file.file, tmp_file)
            tmp_filepath = tmp_file.name

        # Create an output directory for the cropped files
        out_dir = os.path.join(tempfile.gettempdir(), f"crop_{uuid.uuid4().hex}")
        os.makedirs(out_dir, exist_ok=True)
        
        try:
            manifest = crop_folder(
                path=tmp_filepath,
                center_lat=lat,
                center_lon=lon,
                patch_size=patch_size,
                out_dir=out_dir
            )
        except Exception as e:
            raise HTTPException(status_code=500, detail=f"Cropping failed: {str(e)}")
            
        # The script generates .nc files in out_dir.
        generated_files = glob.glob(os.path.join(out_dir, "*.nc"))
        
        if not generated_files:
            raise HTTPException(status_code=500, detail="No cropped files were generated by the script.")
            
        # Upload all generated files to Supabase
        results = []
        for fp in generated_files:
            filename = os.path.basename(fp)
            with open(fp, "rb") as f:
                file_bytes = f.read()
                
            storage_path = f"universal/crops/{uuid.uuid4().hex}/{filename}"
            url = upload_file_to_bucket(file_bytes, storage_path, content_type="application/x-netcdf")
            
            # channel is part of the output name: e.g. base__channel.nc
            # extract the channel name from the filename
            channel_name = filename
            if "__" in filename:
                channel_name = filename.split("__")[-1].replace(".nc", "")
                
            results.append({
                "channel_name": channel_name,
                "url": url,
                "filename": filename
            })
            
        # Cleanup
        os.remove(tmp_filepath)
        shutil.rmtree(out_dir, ignore_errors=True)
        
        return {"success": True, "results": results, "manifest": manifest}

    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
