import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { SidebarNav, StatusBar } from "../components/ui/Dashboard";

// ─────────────────────────────────────────────────────────────
// Rich Technical Explanations for Every Single Block (On Hover)
// ─────────────────────────────────────────────────────────────
interface BlockHoverInfo {
  name: string;
  category: string;
  tech: string;
  purpose: string;
  inputOutput: string;
  mathFormula?: string;
}

const RICH_DESCRIPTIONS: Record<string, BlockHoverInfo> = {
  upload_interface: {
    name: "Upload Interface",
    category: "Frontend UI Component",
    tech: "React 19, HTML5 Drag-and-Drop API, NetCDF / HDF5 Parser",
    purpose: "Accepts raw multi-spectral satellite imagery (.nc / .h5) for TIR and WV channels. The interface uses highly optimized HTML5 Drag-and-Drop combined with an active NetCDF parsing library in the browser to validate spatial dimensions (e.g. 5424x5424 full disk) before transmission. It supports selecting gaps at high temporal resolution (T=0, T=10, T=20) and handles memory-chunked asynchronous uploads for large meteorological datasets seamlessly, ensuring no UI thread blocking.",
    inputOutput: "Input: Raw NetCDF / HDF5 satellite files → Output: Binary array buffers & gap timestamp metadata"
  },
  api_client: {
    name: "API Client",
    category: "Frontend Network Layer",
    tech: "Axios / Fetch API, SSE (Server-Sent Events), Async Promise Handler",
    purpose: "Dispatches HTTP POST requests to the backend FastAPI inference endpoint (/interpolate/single or /interpolate/batch) using FormData encoding. Crucially, it listens to SSE (Server-Sent Events) progress streams and updates real-time job execution state in the UI, mapping GPU inference stages to human-readable progress bars. It also implements automatic exponential backoff and retry logic in case of network instability.",
    inputOutput: "Input: FormData payload with frame files → Output: Async job status stream & JSON result metrics"
  },
  result_viewer: {
    name: "Result Viewer",
    category: "Visualization Component",
    tech: "HTML5 Canvas, CSS Grid, WebGL Overlay",
    purpose: "Displays the synthesized middle frame generated by the IFRNet-GC model alongside ground truth comparisons, side-by-side PNG diffs, and interactive GIF animation playback controls. The viewer leverages WebGL offscreen rendering for extremely smooth 60FPS dual-animation playback, allowing meteorologists to accurately assess cyclonic rotation speed and eye-wall development without rendering lag.",
    inputOutput: "Input: Interpolated frame URL + original frames → Output: Interactive dual animation & frame comparison"
  },
  metrics_dashboard: {
    name: "Metrics Dashboard",
    category: "Quantitative Analysis UI",
    tech: "React State, JetBrains Mono Monospace Readouts",
    purpose: "Renders static and real-time validation metrics evaluating image quality: SSIM (Structural Similarity), PSNR (Peak Signal-to-Noise Ratio), MSE (Mean Squared Error), and FSIM. This dashboard highlights values against strict meteorological thresholds (e.g., PSNR > 32dB) using dynamic color coding, enabling researchers to instantly validate the physical plausibility of the generated atmospheric features.",
    inputOutput: "Input: Evaluation JSON payload → Output: High-contrast metric cards with threshold indicators"
  },
  backend_api: {
    name: "Backend API (Inference Server)",
    category: "Core Backend Service",
    tech: "FastAPI, Uvicorn, Python 3.10+, PyTorch CUDA Execution",
    purpose: "High-performance, asynchronous inference engine. Receives multi-spectral frames and temporal gap parameters via multipart/form-data. It orchestrates dynamic GPU memory allocation, executes the pre-trained PyTorch neural network, handles batching for multiple requests, and writes output NetCDF/PNG files back to disk, all while broadcasting process metrics back via Server-Sent Events.",
    inputOutput: "Input: Multipart form files → Output: JSON response with output image paths & quantitative metric dicts"
  },
  preprocessing_layer: {
    name: "Preprocessing Layer",
    category: "Data Ingestion Pipeline",
    tech: "xarray, netCDF4, NumPy, OpenCV",
    purpose: "Converts raw satellite data into model-ready tensors through 4 sequential, computationally intensive stages: 1) Load massive BT13 & BT8 channels from disk into RAM, 2) Scale brightness temperatures precisely to a [0,1] floating point range to normalize extreme atmospheric cold tops, 3) Composite a 3-channel false-color RGB image (R=BT13, G=BT8, B=avg) to preserve distinct meteorological signatures, 4) Perform a dynamic 256×256 spatial crop tightly around the storm's center of circulation.",
    inputOutput: "Input: NetCDF binary telemetry → Output: Normalized 256×256×3 image patch"
  },
  input_layer: {
    name: "Input Layer & Gap Expansion",
    category: "Tensor Preparation & Innovation",
    tech: "PyTorch Tensor Operations, Spatial Broadcasting",
    purpose: "Constructs 32x padded 3-channel RGB tensors (img0 and img1) required by the downsampling U-Net architecture. THE KEY INNOVATION happens here: Instead of just passing a scalar time value, it expands the scalar temporal gap parameter (t) into a massive 1-channel spatial gap_map tensor matching the exact spatial dimensions of the image. This conditions every single pixel independently, allowing for variable and uneven frame rate intervals.",
    inputOutput: "Input: Normalized images + gap scalar → Output: Tensors img0 (3ch), gap_map (1ch), img1 (3ch)",
    mathFormula: "gap_map(x,y) = t / T_total  where t ∈ [0, T_total]"
  },
  warp_function: {
    name: "Warp Function",
    category: "Differentiable Frame Warping",
    tech: "PyTorch grid_sample, Bilinear Interpolation",
    purpose: "Performs differentiable backward warping of the source frames (img0 and img1) toward the target timestamp using the optical flow vectors estimated by the IFNET cascade. It implements advanced grid sampling with bilinear interpolation, strict boundary mask handling to zero out out-of-bounds pixels, and soft occlusion masks to seamlessly blend overlapping pixels and prevent ghosting artifacts near moving cloud edges.",
    inputOutput: "Input: Image tensor I + Flow field F → Output: Warped image I_warped = BackwardWarp(I, F)"
  },
  ifnet_cascade: {
    name: "IFNET-GC Architecture (Gap-Conditioned Cascade)",
    category: "Neural Network Core",
    tech: "PyTorch, Multi-Scale Cascade Convolutional Network",
    purpose: "The absolute core of the model. It iteratively refines optical flow vectors and occlusion masks across three distinct pyramid scales (Coarse 240ch → Medium 150ch → Fine 90ch) to capture both massive synoptic-scale weather movements and tiny local convective developments. It is deeply conditioned at each scale on the spatial gap_map, making it strictly aware of the temporal distance to synthesize.",
    inputOutput: "Input: img0, img1, gap_map → Output: Fused intermediate frame I_t & refined flow fields"
  },
  scale_4: {
    name: "Scale 4 (Coarse Scale)",
    category: "Coarse Motion Estimation",
    tech: "IFBlock-0 (240 Channels), 2x Strided Conv, 6 Residual Layers, ConvTranspose2D",
    purpose: "Operates at 1/4 spatial resolution to capture large, global motion patterns like the overall rotation of a hurricane. It extracts deep semantic features using 6 massive residual blocks and estimates initial coarse optical flow (flow0) and a coarse occlusion mask (mask0). These are used to blend the first rough approximation of the intermediate frame: m4 = Blend(w0_4, w1_4, mask0).",
    inputOutput: "Input: Downsampled img0, img1, gap_map → Output: flow0 (4ch), mask0 (1ch), warped w0_4 & w1_4"
  },
  scale_2: {
    name: "Scale 2 (Medium Scale)",
    category: "Medium Detail Refinement",
    tech: "IFBlock-1 (150 Channels), Concat(w0_4, w1_4, gap_map), 4 Residual Layers",
    purpose: "Operates at 1/2 spatial resolution. Takes the coarse warped frames (w0_4, w1_4), the upsampled flow0, and the gap_map as a concatenated input. It refines the optical flow fields to flow1 (4ch) and the occlusion mask to mask1 (1ch), correcting errors from the coarse stage and beginning to resolve mesoscale weather features and distinct cloud bands.",
    inputOutput: "Input: flow0 + warped w0_4, w1_4 + gap_map → Output: flow1 (4ch), mask1 (1ch), warped w0_2 & w1_2"
  },
  scale_1: {
    name: "Scale 1 (Fine Scale)",
    category: "Full Resolution Synthesis",
    tech: "IFBlock-2 (90 Channels), Concat(w0_2, w1_2, gap_map), 2 Residual Layers",
    purpose: "Executes at full 1x spatial resolution (256x256). It fuses the fine flow fields (flow2) and the final fine occlusion mask (mask2). This layer is responsible for preserving the sharpest high-frequency details, like individual cumulonimbus overshoots. It synthesizes the final image output: merged = w0_1 × sigmoid(mask2) + w1_1 × (1 - sigmoid(mask2)).",
    inputOutput: "Input: flow1 + warped w0_2, w1_2 + gap_map → Output: Synthesized high-resolution frame image"
  },
  training_losses: {
    name: "Training Losses",
    category: "Multi-Objective Optimization",
    tech: "PyTorch Autograd Loss Function Composite",
    purpose: "A highly complex multi-objective optimization function that computes gradients for backpropagation. It mathematically balances 6 distinct loss targets to ensure the synthesized satellite imagery is physically accurate, structurally sound, and visually sharp, preventing the typical blurring associated with standard MSE loss in autoencoders.",
    inputOutput: "Input: Predicted frame vs Ground truth → Output: Scalar total loss for backpropagation"
  },
  load_satellite_data: {
    name: "Load Satellite Data", category: "Preprocessing Step", tech: "NetCDF Reader", purpose: "Reads GOES-16/19 ABI L1b Radiances (specifically Band 8 Water Vapor and Band 13 Clean IR). These specific bands are chosen because they track upper-level moisture and cloud top temperatures, which are critical for interpolating severe weather dynamics.", inputOutput: "Binary File → Raw Numpy Arrays"
  },
  bt_normalization: {
    name: "Brightness Temp Normalization", category: "Preprocessing Step", tech: "Min-Max Scaling", purpose: "Clips raw physical kelvin temperatures strictly to [200K, 300K] (which represents the typical range from cold high-altitude cloud tops to warm ocean surfaces) and min-max normalizes the values to a [0,1] float tensor to stabilize neural network gradients.", inputOutput: "Kelvin Array → [0,1] Float Tensor"
  },
  rgb_composite: {
    name: "RGB Composite", category: "Preprocessing Step", tech: "Channel Stacking", purpose: "Creates a false-color representation tailored for computer vision models where Red=BT13 (Cloud Tops), Green=BT8 (Water Vapor), and Blue=(R+G)/2 (Average). This 3-channel structure allows the network to leverage standard 2D Convolutional kernels effectively.", inputOutput: "1D Channels → 3-Channel RGB Image"
  },
  spatial_crop: {
    name: "Spatial Crop", category: "Preprocessing Step", tech: "Array Slicing", purpose: "Calculates the center of mass of the cyclonic system and crops a tight 256x256 bounding box around the active hurricane/storm core, removing useless clear-sky background and focusing the network's attention purely on complex fluid dynamics.", inputOutput: "Full Disk Image → 256x256 Patch"
  },
  img0_padded: {
    name: "Frame T=0 (Padded)", category: "Input Tensor", tech: "Reflect Padding", purpose: "The initial timeframe satellite image tensor. It undergoes Reflect Padding to ensure its spatial dimensions are a perfect multiple of 32 (e.g. 256x256), which is a hard mathematical requirement for the downsampling and upsampling operations in the U-Net skip connections to perfectly align.", inputOutput: "256x256 → 256x256 (32x compatible)"
  },
  img1_padded: {
    name: "Frame T=1 (Padded)", category: "Input Tensor", tech: "Reflect Padding", purpose: "The final timeframe satellite image tensor. Like img0, it is reflect-padded. The network uses img0 and img1 to understand the total motion vector field that occurred over the 10 or 20 minute observational gap.", inputOutput: "256x256 → 256x256 (32x compatible)"
  },
  gap_map: {
    name: "Gap Map Tensor", category: "Temporal Conditioning", tech: "Spatial Broadcast", purpose: "A massive 1-channel tensor identically sized to the images, filled entirely with the normalized scalar 't'. This tells the spatial convolutions exactly which intermediate frame to generate (e.g., t=0.5 for exactly halfway), acting as a dense positional encoding for time.", inputOutput: "Scalar t ∈ (0,1) → HxWx1 Tensor"
  },
  charbonnier_loss: {
    name: "Charbonnier Loss", category: "Loss Function", tech: "Robust L1 Penalty", purpose: "A differentiable, smoothed approximation of L1 loss. It handles outliers (like sudden lightning flashes or sensor noise) much better than standard L2/MSE loss, ensuring robust, pixel-wise radiometric reconstruction without blurring.", inputOutput: "Predicted & Target → Scalar Penalty"
  },
  multiscale_loss: {
    name: "Multiscale Loss", category: "Loss Function", tech: "Pyramid Supervision", purpose: "Applies the loss function independently at scale 4 (coarse), scale 2 (medium), and scale 1 (fine). This deeply supervises intermediate features and forces the network to learn accurate motion fields at every level of the pyramid, preventing cascading errors.", inputOutput: "Multi-res Predictions → Scalar Penalty"
  },
  ssim_loss: {
    name: "SSIM Loss", category: "Loss Function", tech: "Structural Similarity", purpose: "Maximizes the structural and perceptual similarity between the generated image and the ground truth. It focuses on luminance, contrast, and structure rather than just absolute pixel errors, aligning the loss with human visual perception of cloud shapes.", inputOutput: "Predicted & Target → Structural Penalty"
  },
  laplacian_loss: {
    name: "Laplacian Loss", category: "Loss Function", tech: "High-frequency Edge Filter", purpose: "Extracts high-frequency edges using a Laplacian filter and penalizes the network if the predicted edges don't match the ground truth. This is critical for preventing the blurry predictions common in autoencoders and forcing the reconstruction of sharp storm eye walls.", inputOutput: "Edge Maps → Scalar Penalty"
  },
  edge_aware_loss: {
    name: "Edge-aware Loss", category: "Loss Function", tech: "Gradient Weighted", purpose: "Calculates spatial gradients (Sobel filters) and weights the loss higher in areas with sharp gradients. It forces the model to dedicate more representational capacity to complex convective boundaries rather than uniform flat cloud decks.", inputOutput: "Spatial Gradients → Scalar Penalty"
  },
  smoothness_loss: {
    name: "Smoothness Loss", category: "Loss Function", tech: "Total Variation", purpose: "Calculates the spatial derivatives of the predicted optical flow fields and applies a Total Variation penalty. This ensures the predicted motion vectors are locally smooth and physically plausible, preventing chaotic, noisy flow fields.", inputOutput: "Flow Field Gradients → Scalar Penalty"
  }
};



import { memo, useMemo } from "react";
import { ReactFlow, ReactFlowProvider, Background, Handle, Position, type Edge, type Node, MarkerType } from "@xyflow/react";
import '@xyflow/react/dist/style.css';

const pillStyle = {
  background: "rgba(12, 15, 22, 0.5)",
  backdropFilter: "blur(8px)",
  WebkitBackdropFilter: "blur(8px)",
  color: "#F0F4FF",
  border: "1px solid rgba(255, 107, 53, 0.4)",
  borderRadius: "8px",
  padding: "1rem 1.25rem",
  fontSize: "14px",
  fontWeight: 700,
  textAlign: "center" as const,
  boxShadow: "0 0 10px rgba(255, 107, 53, 0.15)",
};

const scaleCardStyle = {
  background: "rgba(20, 24, 34, 0.3)",
  backdropFilter: "blur(10px)",
  WebkitBackdropFilter: "blur(10px)",
  border: "1px solid rgba(255, 255, 255, 0.2)",
  borderRadius: "10px",
  padding: "1.25rem",
  display: "flex",
  flexDirection: "column" as const,
  justifyContent: "space-between",
  gap: "1rem",
};

// --- CUSTOM NODES ---

const PreprocessingNode = ({ data }: any) => (
  <div
    className="cursor-target"
    onMouseEnter={() => data.setHoveredKey("preprocessing_layer")}
    onMouseLeave={() => data.setHoveredKey(null)}
    style={{
      background: "rgba(12, 15, 22, 0.4)",
      backdropFilter: "blur(14px) saturate(1.2)",
      boxShadow: "0 8px 32px rgba(0,0,0,0.4)",
      border: "1px dashed rgba(255, 255, 255, 0.2)",
      borderRadius: "14px",
      padding: "1.4rem",
      display: "flex",
      flexDirection: "column",
      gap: "0.6rem",
      width: 250,
    }}
  >
    <div style={{ fontSize: "16px", fontWeight: 800, color: "#FFFFFF", textAlign: "center", marginBottom: "0.5rem" }}>
      Preprocessing Layer
    </div>
    <div className="cursor-target" onMouseEnter={(e) => { e.stopPropagation(); data.setHoveredKey("load_satellite_data"); }} onMouseLeave={(e) => { e.stopPropagation(); data.setHoveredKey("preprocessing_layer"); }} style={pillStyle}>
      Load Satellite Data<br /><span style={{ fontSize: "9px", opacity: 0.8 }}>BT13 + BT8 from NetCDF</span>
    </div>
    <div style={{ textAlign: "center", color: "#FFFFFF", fontSize: "10px", lineHeight: 1 }}>↓</div>
    <div className="cursor-target" onMouseEnter={(e) => { e.stopPropagation(); data.setHoveredKey("bt_normalization"); }} onMouseLeave={(e) => { e.stopPropagation(); data.setHoveredKey("preprocessing_layer"); }} style={pillStyle}>
      Brightness Temp Normalization<br /><span style={{ fontSize: "9px", opacity: 0.8 }}>scaled to [0,1]</span>
    </div>
    <div style={{ textAlign: "center", color: "#FFFFFF", fontSize: "10px", lineHeight: 1 }}>↓</div>
    <div className="cursor-target" onMouseEnter={(e) => { e.stopPropagation(); data.setHoveredKey("rgb_composite"); }} onMouseLeave={(e) => { e.stopPropagation(); data.setHoveredKey("preprocessing_layer"); }} style={pillStyle}>
      RGB Composite<br /><span style={{ fontSize: "9px", opacity: 0.8 }}>R=BT13, G=BT8, B=avg</span>
    </div>
    <div style={{ textAlign: "center", color: "#FFFFFF", fontSize: "10px", lineHeight: 1 }}>↓</div>
    <div className="cursor-target" onMouseEnter={(e) => { e.stopPropagation(); data.setHoveredKey("spatial_crop"); }} onMouseLeave={(e) => { e.stopPropagation(); data.setHoveredKey("preprocessing_layer"); }} style={pillStyle}>
      Spatial Crop<br /><span style={{ fontSize: "9px", opacity: 0.8 }}>256×256 patch storm region</span>
    </div>
    <Handle type="source" position={Position.Bottom} id="out" style={{ background: 'transparent', border: 'none' }} />
  </div>
);

const InputLayerNode = ({ data }: any) => (
  <div
    className="cursor-target"
    onMouseEnter={() => data.setHoveredKey("input_layer")}
    onMouseLeave={() => data.setHoveredKey(null)}
    style={{
      background: "rgba(12, 15, 22, 0.4)",
      backdropFilter: "blur(14px) saturate(1.2)",
      boxShadow: "0 8px 32px rgba(0,0,0,0.4)",
      border: "1px dashed rgba(255, 255, 255, 0.2)",
      borderRadius: "14px",
      padding: "1.4rem",
      display: "flex",
      flexDirection: "column",
      gap: "0.6rem",
      width: 250,
    }}
  >
    <div style={{ fontSize: "16px", fontWeight: 800, color: "#FFFFFF", textAlign: "center", marginBottom: "0.5rem" }}>
      Input Layer
    </div>
    <div style={{ position: 'relative' }}>
      <Handle type="target" position={Position.Left} id="in-img0" style={{ background: 'transparent', border: 'none', left: -20 }} />
      <div className="cursor-target" onMouseEnter={(e) => { e.stopPropagation(); data.setHoveredKey("img0_padded"); }} onMouseLeave={(e) => { e.stopPropagation(); data.setHoveredKey("input_layer"); }} style={pillStyle}>
        img0 padded<br /><span style={{ fontSize: "9px", opacity: 0.8 }}>3-channel RGB (32x pad)</span>
      </div>
      <Handle type="source" position={Position.Right} id="out-img0" style={{ background: 'transparent', border: 'none', right: -20 }} />
    </div>

    <div style={{ position: 'relative' }}>
      <Handle type="target" position={Position.Left} id="in-gapmap" style={{ background: 'transparent', border: 'none', left: -20 }} />
      <div className="cursor-target" onMouseEnter={(e) => { e.stopPropagation(); data.setHoveredKey("gap_map"); }} onMouseLeave={(e) => { e.stopPropagation(); data.setHoveredKey("input_layer"); }} style={pillStyle}>
        gap_map<br /><span style={{ fontSize: "9px", opacity: 0.8 }}>1-channel temporal distance</span>
      </div>
      <Handle type="source" position={Position.Right} id="out-gapmap" style={{ background: 'transparent', border: 'none', right: -20 }} />
    </div>

    <div style={{ position: 'relative' }}>
      <Handle type="target" position={Position.Left} id="in-img1" style={{ background: 'transparent', border: 'none', left: -20 }} />
      <div className="cursor-target" onMouseEnter={(e) => { e.stopPropagation(); data.setHoveredKey("img1_padded"); }} onMouseLeave={(e) => { e.stopPropagation(); data.setHoveredKey("input_layer"); }} style={pillStyle}>
        img1 padded<br /><span style={{ fontSize: "9px", opacity: 0.8 }}>3-channel RGB (32x pad)</span>
      </div>
      <Handle type="source" position={Position.Right} id="out-img1" style={{ background: 'transparent', border: 'none', right: -20 }} />
    </div>
  </div>
);

const WarpFunctionNode = ({ data }: any) => (
  <div
    className="cursor-target"
    onMouseEnter={() => data.setHoveredKey("warp_function")}
    onMouseLeave={() => data.setHoveredKey(null)}
    style={{
      background: "rgba(25, 15, 10, 0.4)",
      backdropFilter: "blur(14px) saturate(1.2)",
      boxShadow: "0 8px 32px rgba(0,0,0,0.4)",
      border: "1px dashed rgba(255, 107, 53, 0.6)",
      borderRadius: "14px",
      padding: "1.4rem",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      textAlign: "center",
      width: 180,
      height: 180,
      position: "relative"
    }}
  >
    <Handle type="target" position={Position.Left} id="in-gapmap" style={{ top: '50%', background: 'transparent', border: 'none', left: -20 }} />
    
    <div style={{ fontSize: "18px", fontWeight: 800, color: "#9a3412" }}>
      Warp Function
    </div>
    <div style={{ fontSize: "13px", color: "#c2410c", marginTop: "0.5rem", lineHeight: 1.4 }}>
      Grid Sampling,<br />Boundary Mask,<br />Partial Warp Handling
    </div>
    
    <Handle type="source" position={Position.Right} id="out" style={{ background: 'transparent', border: 'none', right: -20 }} />
  </div>
);

const IFNETNode = ({ data }: any) => (
  <div
    className="cursor-target"
    onMouseEnter={() => data.setHoveredKey("ifnet_cascade")}
    onMouseLeave={() => data.setHoveredKey(null)}
    style={{
      background: "rgba(12, 15, 22, 0.4)",
      backdropFilter: "blur(14px) saturate(1.2)",
      boxShadow: "0 8px 32px rgba(0,0,0,0.4)",
      border: "1px dashed rgba(255, 255, 255, 0.2)",
      borderRadius: "16px",
      padding: "1.4rem",
      display: "flex",
      flexDirection: "column",
      gap: "1rem",
      width: 650
    }}
  >
    <div style={{ fontSize: "18px", fontWeight: 800, color: "#FFFFFF", textAlign: "center" }}>
      IFNET-GC Architecture (Gap-Conditioned Multi-scale Cascade)
    </div>

    <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: "0.75rem", flex: 1, position: 'relative' }}>
      
      {/* Scale 4 (Coarse) */}
      <div style={{ position: 'relative' }}>
        <Handle type="target" position={Position.Left} id="in-scale4" style={{ top: '50%', background: 'transparent', border: 'none', left: -40 }} />
        <div className="cursor-target" onMouseEnter={(e) => { e.stopPropagation(); data.setHoveredKey("scale_4"); }} onMouseLeave={(e) => { e.stopPropagation(); data.setHoveredKey("ifnet_cascade"); }} style={{...scaleCardStyle, height: '100%'}}>
          <div style={{ fontSize: "14px", fontWeight: 800, color: "#FFFFFF", textAlign: "center" }}>Scale 4 (Coarse)</div>
          <div style={pillStyle}>
            IFBlock-0<br /><span style={{ fontSize: "10px" }}>Channels: 240</span>
          </div>
          <div style={{ fontSize: "10px", color: "#FFFFFF", lineHeight: 1.3 }}>
            • conv0 (2x Strided Conv)<br />
            • convblock (6 Residual Layers)<br />
            • lastconv (ConvTranspose2D)
          </div>
          <div style={{ fontSize: "9px", background: "rgba(255, 255, 255, 0.1)", padding: "3px", borderRadius: "4px", color: "#FFFFFF", textAlign: "center", fontWeight: 700 }}>
            m4 = Blend(w0_4, w1_4, mask0)
          </div>
        </div>
      </div>

      {/* Scale 2 (Medium) */}
      <div style={{ position: 'relative' }}>
        <Handle type="target" position={Position.Bottom} id="in-losses" style={{ background: 'transparent', border: 'none', bottom: -40 }} />
        <div className="cursor-target" onMouseEnter={(e) => { e.stopPropagation(); data.setHoveredKey("scale_2"); }} onMouseLeave={(e) => { e.stopPropagation(); data.setHoveredKey("ifnet_cascade"); }} style={{...scaleCardStyle, height: '100%'}}>
          <div style={{ fontSize: "14px", fontWeight: 800, color: "#FFFFFF", textAlign: "center" }}>Scale 2 (Medium)</div>
          <div style={{ fontSize: "9px", color: "#8E9BB0", textAlign: "center" }}>concat(w0_4, w1_4, gap_map)</div>
          <div style={pillStyle}>
            IFBlock-1<br /><span style={{ fontSize: "10px" }}>Channels: 150</span>
          </div>
          <div style={{ fontSize: "10px", color: "#FFFFFF", lineHeight: 1.3 }}>
            • conv0 (Refinement Conv)<br />
            • convblock (4 Residual Layers)<br />
            • lastconv (Flow Refinement)
          </div>
          <div style={{ fontSize: "9px", background: "rgba(255, 255, 255, 0.1)", padding: "3px", borderRadius: "4px", color: "#FFFFFF", textAlign: "center", fontWeight: 700 }}>
            m2 = Blended(w0_2, w1_2, mask1)
          </div>
        </div>
      </div>

      {/* Scale 1 (Fine) */}
      <div style={{ position: 'relative' }}>
        <div className="cursor-target" onMouseEnter={(e) => { e.stopPropagation(); data.setHoveredKey("scale_1"); }} onMouseLeave={(e) => { e.stopPropagation(); data.setHoveredKey("ifnet_cascade"); }} style={{...scaleCardStyle, height: '100%'}}>
          <div style={{ fontSize: "14px", fontWeight: 800, color: "#FFFFFF", textAlign: "center" }}>Scale 1 (Fine)</div>
          <div style={{ fontSize: "9px", color: "#8E9BB0", textAlign: "center" }}>concat(w0_2, w1_2, gap_map)</div>
          <div style={pillStyle}>
            IFBlock-2<br /><span style={{ fontSize: "10px" }}>Channels: 90</span>
          </div>
          <div style={{ fontSize: "10px", color: "#FFFFFF", lineHeight: 1.3 }}>
            • conv0 (High-res Conv)<br />
            • convblock (2 Residual Layers)<br />
            • lastconv (Final Flow Fused)
          </div>
          <div style={{ fontSize: "8px", background: "rgba(255, 255, 255, 0.1)", padding: "3px", borderRadius: "4px", color: "#FFFFFF", textAlign: "center", fontWeight: 700 }}>
            merged = w0_1 × sigmoid + w1_1 × (1-sigmoid)
          </div>
        </div>
      </div>

      {/* Internal SVG Arrows */}
      <div style={{ position: 'absolute', left: "33.33%", top: '50%', transform: 'translate(-50%, -50%)', zIndex: 10 }}>
        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#8ba1c5" strokeWidth="2" strokeLinecap="square" strokeLinejoin="miter">
          <line x1="0" y1="12" x2="22" y2="12" />
          <polyline points="16 6 22 12 16 18" />
        </svg>
      </div>
      <div style={{ position: 'absolute', left: "66.66%", top: '50%', transform: 'translate(-50%, -50%)', zIndex: 10 }}>
        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#8ba1c5" strokeWidth="2" strokeLinecap="square" strokeLinejoin="miter">
          <line x1="0" y1="12" x2="22" y2="12" />
          <polyline points="16 6 22 12 16 18" />
        </svg>
      </div>

    </div>
  </div>
);

const LossesNode = ({ data }: any) => (
  <div
    className="cursor-target"
    onMouseEnter={() => data.setHoveredKey("training_losses")}
    onMouseLeave={() => data.setHoveredKey(null)}
    style={{
      background: "rgba(12, 15, 22, 0.4)",
      backdropFilter: "blur(14px) saturate(1.2)",
      boxShadow: "0 8px 32px rgba(0,0,0,0.4)",
      border: "1px dashed rgba(255, 255, 255, 0.2)",
      borderRadius: "14px",
      padding: "1.4rem",
      display: "flex",
      flexDirection: "column",
      gap: "0.8rem",
      width: 500
    }}
  >
    <Handle type="source" position={Position.Right} id="out" style={{ background: 'transparent', border: 'none', right: -20, top: '50%' }} />
    <div style={{ fontSize: "16px", fontWeight: 800, color: "#FFFFFF", textAlign: "center", marginBottom: "0.5rem" }}>
      Training Losses
    </div>
    <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: "0.4rem" }}>
      <div className="cursor-target" onMouseEnter={(e) => { e.stopPropagation(); data.setHoveredKey("charbonnier_loss"); }} onMouseLeave={(e) => { e.stopPropagation(); data.setHoveredKey("training_losses"); }} style={pillStyle}>Charbonnier Loss<br /><span style={{ fontSize: "8px", opacity: 0.8 }}>weight(1) Robust pixel</span></div>
      <div className="cursor-target" onMouseEnter={(e) => { e.stopPropagation(); data.setHoveredKey("multiscale_loss"); }} onMouseLeave={(e) => { e.stopPropagation(); data.setHoveredKey("training_losses"); }} style={pillStyle}>Multiscale Loss<br /><span style={{ fontSize: "8px", opacity: 0.8 }}>weight(0.5) coarse to fine</span></div>
      <div className="cursor-target" onMouseEnter={(e) => { e.stopPropagation(); data.setHoveredKey("ssim_loss"); }} onMouseLeave={(e) => { e.stopPropagation(); data.setHoveredKey("training_losses"); }} style={pillStyle}>SSIM Loss<br /><span style={{ fontSize: "8px", opacity: 0.8 }}>weight(0.6) structure</span></div>
      <div className="cursor-target" onMouseEnter={(e) => { e.stopPropagation(); data.setHoveredKey("laplacian_loss"); }} onMouseLeave={(e) => { e.stopPropagation(); data.setHoveredKey("training_losses"); }} style={pillStyle}>Laplacian Loss<br /><span style={{ fontSize: "8px", opacity: 0.8 }}>weight(0.3) edge sharp</span></div>
      <div className="cursor-target" onMouseEnter={(e) => { e.stopPropagation(); data.setHoveredKey("edge_aware_loss"); }} onMouseLeave={(e) => { e.stopPropagation(); data.setHoveredKey("training_losses"); }} style={pillStyle}>Edge-aware Loss<br /><span style={{ fontSize: "8px", opacity: 0.8 }}>weight(0.4) penalty</span></div>
      <div className="cursor-target" onMouseEnter={(e) => { e.stopPropagation(); data.setHoveredKey("smoothness_loss"); }} onMouseLeave={(e) => { e.stopPropagation(); data.setHoveredKey("training_losses"); }} style={pillStyle}>Smoothness Loss<br /><span style={{ fontSize: "8px", opacity: 0.8 }}>weight(0.1) flow field</span></div>
    </div>
  </div>
);

const nodeTypes = {
  preprocessing: PreprocessingNode,
  inputLayer: InputLayerNode,
  warp: WarpFunctionNode,
  ifnet: IFNETNode,
  losses: LossesNode
};

const ArchitectureFlow = memo(function ArchitectureFlow({ setHoveredKey }: { setHoveredKey: (k: string | null) => void }) {
  const initialNodes: Node[] = useMemo(() => [
    {
      id: "node-preprocessing",
      type: "preprocessing",
      position: { x: 50, y: 50 },
      data: { setHoveredKey },
    },
    {
      id: "node-inputs",
      type: "inputLayer",
      position: { x: 380, y: 110 },
      data: { setHoveredKey },
    },
    {
      id: "node-warp",
      type: "warp",
      position: { x: 700, y: 160 },
      data: { setHoveredKey },
    },
    {
      id: "node-ifnet",
      type: "ifnet",
      position: { x: 950, y: 80 },
      data: { setHoveredKey },
    },
    {
      id: "node-losses",
      type: "losses",
      position: { x: 380, y: 520 },
      data: { setHoveredKey },
    }
  ], [setHoveredKey]);

  const edgeStyle = useMemo(() => ({ stroke: '#8ba1c5', strokeWidth: 2 }), []);
  const markerEnd = useMemo(() => ({ type: MarkerType.ArrowClosed, color: '#8ba1c5' }), []);

  const initialEdges: Edge[] = useMemo(() => [
    { id: 'e-pre-img0', source: 'node-preprocessing', sourceHandle: 'out', target: 'node-inputs', targetHandle: 'in-img0', type: 'step', style: edgeStyle, markerEnd },
    { id: 'e-pre-gapmap', source: 'node-preprocessing', sourceHandle: 'out', target: 'node-inputs', targetHandle: 'in-gapmap', type: 'step', style: edgeStyle, markerEnd },
    { id: 'e-pre-img1', source: 'node-preprocessing', sourceHandle: 'out', target: 'node-inputs', targetHandle: 'in-img1', type: 'step', style: edgeStyle, markerEnd },
    
    { id: 'e-in0-warp', source: 'node-inputs', sourceHandle: 'out-img0', target: 'node-warp', targetHandle: 'in-gapmap', type: 'step', style: edgeStyle, markerEnd },
    { id: 'e-ingap-warp', source: 'node-inputs', sourceHandle: 'out-gapmap', target: 'node-warp', targetHandle: 'in-gapmap', type: 'step', style: edgeStyle, markerEnd },
    { id: 'e-in1-warp', source: 'node-inputs', sourceHandle: 'out-img1', target: 'node-warp', targetHandle: 'in-gapmap', type: 'step', style: edgeStyle, markerEnd },

    { id: 'e-warp-ifnet', source: 'node-warp', sourceHandle: 'out', target: 'node-ifnet', targetHandle: 'in-scale4', type: 'step', style: edgeStyle, markerEnd },
    


    // Losses edge
    { id: 'e-losses-ifnet', source: 'node-losses', sourceHandle: 'out', target: 'node-ifnet', targetHandle: 'in-losses', type: 'step', style: edgeStyle, markerEnd },
  ], [edgeStyle, markerEnd]);

  return (
    <ReactFlow 
      nodes={initialNodes} 
      edges={initialEdges} 
      nodeTypes={nodeTypes}
      fitView
      fitViewOptions={{ padding: 0.2 }}
      nodesConnectable={false}
      nodesDraggable={true}
      elementsSelectable={false}
      proOptions={{ hideAttribution: true }}
    >
      <Background color="#1e293b" gap={20} size={1} />
    </ReactFlow>
  );
});

export default function ArchitecturePage() {
  const navigate = useNavigate();
  const [hoveredKey, setHoveredKey] = useState<string | null>(null);
  const [mousePos, setMousePos] = useState({ x: 0, y: 0 });

  const activeInfo = hoveredKey ? RICH_DESCRIPTIONS[hoveredKey] : null;

  return (
    <div 
      onMouseMove={(e) => setMousePos({ x: e.clientX, y: e.clientY })}
      style={{
        minHeight: "100vh",
        width: "100vw",
        background: "transparent",
        color: "#0f172a",
        fontFamily: "'Space Grotesk', sans-serif",
        boxSizing: "border-box",
        display: "flex",
        flexDirection: "column",
        position: "relative",
    }}>
      <StatusBar running={false} done={false} progress={0} />

      <div style={{
        display: "flex",
        flexDirection: "row",
        flex: 1,
        minHeight: 0,
        padding: "2rem",
        gap: "2rem"
      }}>
      
      <SidebarNav active="architecture" onNavigate={(route) => navigate(route)} />

      <div style={{ flex: 1, display: "flex", flexDirection: "column", minWidth: 0, position: "relative" }}>
      {/* Top Header Bar */}
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: "0.75rem", borderBottom: "2px solid rgba(255, 255, 255, 0.2)", paddingBottom: "0.5rem", flexShrink: 0 }}>
        <div>
          <div style={{ fontSize: "22px", fontWeight: 800, color: "#ffffff", letterSpacing: "-0.01em" }}>
            Architecture Diagram of the proposed solution:
          </div>
          <div style={{ fontSize: "12px", color: "#94a3b8", marginTop: 2 }}>
            Gap-Conditioned Multi-scale Cascade (IFNET-GC) · INSAT-3DS / GOES-19 Pipeline
          </div>
        </div>
      </div>

      {/* Floating Tooltip following mouse */}
      {activeInfo && (
        <div style={{
          position: "fixed",
          top: mousePos.y > window.innerHeight * 0.45 ? undefined : mousePos.y + 20,
          bottom: mousePos.y > window.innerHeight * 0.45 ? window.innerHeight - mousePos.y + 20 : undefined,
          left: mousePos.x > window.innerWidth * 0.55 ? undefined : mousePos.x + 20,
          right: mousePos.x > window.innerWidth * 0.55 ? window.innerWidth - mousePos.x + 20 : undefined,
          width: "650px",
          background: "rgba(10, 15, 25, 0.95)",
          backdropFilter: "blur(20px)",
          border: "1px solid rgba(255, 255, 255, 0.3)",
          borderRadius: "14px",
          padding: "1.5rem",
          color: "#f8fafc",
          boxShadow: "0 20px 50px rgba(0,0,0,0.8), 0 0 30px rgba(255, 255, 255, 0.1)",
          zIndex: 9999,
          pointerEvents: "none",
          animation: "slide-up-fade 0.1s ease-out",
          transform: "scale(0.85)"
        }}>
          <div style={{ fontSize: "12px", fontWeight: 700, color: "#93c5fd", textTransform: "uppercase", letterSpacing: "0.08em" }}>
            {activeInfo.category}
          </div>
          <div style={{ fontSize: "20px", fontWeight: 800, color: "#ffffff", marginTop: 4, marginBottom: 8 }}>
            {activeInfo.name}
          </div>
          <div style={{ fontSize: "13px", color: "#F0F4FF", fontWeight: 600, marginBottom: 12, background: "rgba(255, 255, 255, 0.1)", padding: "6px 10px", borderRadius: "6px" }}>
            <span style={{opacity: 0.7}}>Tech:</span> {activeInfo.tech}
          </div>
          <p style={{ fontSize: "14px", color: "#cbd5e1", lineHeight: 1.6, margin: 0, marginBottom: 12 }}>
            {activeInfo.purpose}
          </p>
          <div style={{ fontSize: "13px", color: "#FFFFFF", fontWeight: 700, padding: "6px 10px", background: "rgba(147, 197, 253, 0.1)", borderRadius: "6px" }}>
            {activeInfo.inputOutput}
          </div>
          {activeInfo.mathFormula && (
            <div style={{ marginTop: 10, fontSize: "13px", fontFamily: "'JetBrains Mono', monospace", color: "#fde047", background: "rgba(234,179,8,0.15)", padding: "6px 10px", borderRadius: "4px" }}>
              {activeInfo.mathFormula}
            </div>
          )}
          {hoveredKey === "load_satellite_data" && (
            <div style={{ marginTop: 12, borderRadius: "8px", overflow: "hidden", border: "1px solid rgba(255, 107, 53, 0.3)", background: "#0d1117" }}>
              <video src="/load_satellite_data.mp4" autoPlay loop muted playsInline style={{ width: "100%", height: "auto", display: "block" }} />
            </div>
          )}
          {hoveredKey === "bt_normalization" && (
            <div style={{ marginTop: 12, borderRadius: "8px", overflow: "hidden", border: "1px solid rgba(255, 107, 53, 0.3)", background: "#0d1117" }}>
              <video src="/brightness_temp_normalisation.mp4" autoPlay loop muted playsInline style={{ width: "100%", height: "auto", display: "block" }} />
            </div>
          )}
          {hoveredKey === "rgb_composite" && (
            <div style={{ marginTop: 12, borderRadius: "8px", overflow: "hidden", border: "1px solid rgba(255, 107, 53, 0.3)", background: "#0d1117" }}>
              <video src="/rgb_composite.mp4" autoPlay loop muted playsInline style={{ width: "100%", height: "auto", display: "block" }} />
            </div>
          )}
          {hoveredKey === "spatial_crop" && (
            <div style={{ marginTop: 12, borderRadius: "8px", overflow: "hidden", border: "1px solid rgba(255, 107, 53, 0.3)", background: "#0d1117" }}>
              <video src="/spatial_crop.mp4" autoPlay loop muted playsInline style={{ width: "100%", height: "auto", display: "block" }} />
            </div>
          )}
          {(hoveredKey === "img0_padded" || hoveredKey === "img1_padded") && (
            <div style={{ marginTop: 12, borderRadius: "8px", overflow: "hidden", border: "1px solid rgba(255, 107, 53, 0.3)", background: "#0d1117" }}>
              <video src="/img_padded.mp4" autoPlay loop muted playsInline style={{ width: "100%", height: "auto", display: "block" }} />
            </div>
          )}
          {hoveredKey === "gap_map" && (
            <div style={{ marginTop: 12, borderRadius: "8px", overflow: "hidden", border: "1px solid rgba(255, 107, 53, 0.3)", background: "#0d1117" }}>
              <video src="/gap_map.mp4" autoPlay loop muted playsInline style={{ width: "100%", height: "auto", display: "block" }} />
            </div>
          )}
          {hoveredKey === "warp_function" && (
            <div style={{ marginTop: 12, borderRadius: "8px", overflow: "hidden", border: "1px solid rgba(255, 107, 53, 0.3)", background: "#0d1117" }}>
              <video src="/wrap-animation.mp4" autoPlay loop muted playsInline style={{ width: "100%", height: "auto", display: "block" }} />
            </div>
          )}
          {hoveredKey === "scale_4" && (
            <div style={{ marginTop: 12, borderRadius: "8px", overflow: "hidden", border: "1px solid rgba(255, 107, 53, 0.3)", background: "#0d1117" }}>
              <video src="/scale4.mp4" autoPlay loop muted playsInline style={{ width: "100%", height: "auto", display: "block" }} />
            </div>
          )}
          {hoveredKey === "scale_2" && (
            <div style={{ marginTop: 12, borderRadius: "8px", overflow: "hidden", border: "1px solid rgba(255, 107, 53, 0.3)", background: "#0d1117" }}>
              <video src="/scale2.mp4" autoPlay loop muted playsInline style={{ width: "100%", height: "auto", display: "block" }} />
            </div>
          )}
          {hoveredKey === "scale_1" && (
            <div style={{ marginTop: 12, borderRadius: "8px", overflow: "hidden", border: "1px solid rgba(255, 107, 53, 0.3)", background: "#0d1117" }}>
              <video src="/scale1.mp4" autoPlay loop muted playsInline style={{ width: "100%", height: "auto", display: "block" }} />
            </div>
          )}
        </div>
      )}

      {/* Main Diagram Canvas - React Flow */}
      <style>
        {`
          #architecture-grid,
          #architecture-grid .react-flow__pane,
          #architecture-grid .react-flow__node,
          #architecture-grid .react-flow__edge,
          #architecture-grid .cursor-target {
            cursor: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='32' height='32' viewBox='0 0 32 32'%3E%3Ccircle cx='16' cy='16' r='8' fill='rgba(255,0,0,0.4)'/%3E%3Ccircle cx='16' cy='16' r='4' fill='%23ff0000'/%3E%3Ccircle cx='16' cy='16' r='2' fill='%23ffffff'/%3E%3C/svg%3E") 16 16, crosshair !important;
          }
        `}
      </style>
      <div id="architecture-grid" style={{
        flex: 1,
        minHeight: 0,
        background: "rgba(10, 13, 20, 0.4)",
        backdropFilter: "blur(16px) saturate(1.2)",
        WebkitBackdropFilter: "blur(16px) saturate(1.2)",
        boxShadow: "0 8px 32px rgba(0,0,0,0.5)",
        borderRadius: "16px",
        border: "1px solid rgba(255, 255, 255, 0.12)",
        position: "relative",
        overflow: "hidden",
        cursor: "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='32' height='32' viewBox='0 0 32 32'%3E%3Ccircle cx='16' cy='16' r='8' fill='rgba(255,0,0,0.4)'/%3E%3Ccircle cx='16' cy='16' r='4' fill='%23ff0000'/%3E%3Ccircle cx='16' cy='16' r='2' fill='%23ffffff'/%3E%3C/svg%3E\") 16 16, crosshair"
      }}>
        <ReactFlowProvider>
          <ArchitectureFlow setHoveredKey={setHoveredKey} />
        </ReactFlowProvider>
      </div>

      </div>
      </div>
    </div>
  );
}

